name: Update Assistant to OpenAI

on:
  push:
    paths:
      - assistant_config.json

jobs:
  update-assistant:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Assistant on OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          CONFIG_FILE="assistant_config.json"

          # Check if the config file exists
          if [ ! -f "$CONFIG_FILE" ]; then
            echo "Configuration file not found!"
            exit 1
          fi

          # Validate the JSON format
          if ! jq empty "$CONFIG_FILE"; then
            echo "Invalid JSON format in $CONFIG_FILE"
            exit 1
          fi

          # Remove 'id' field from the JSON to avoid errors
          jq 'del(.id)' "$CONFIG_FILE" > temp_config.json

          # POST request to update the assistant
          echo "Updating the assistant..."
          curl -s -X POST "https://api.openai.com/v1/assistants" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -H "OpenAI-Beta: assistants=v2" \
            -d @temp_config.json \
            -o update_response.json

          # Check if there was an error during the request
          if jq '.error' update_response.json > /dev/null; then
            echo "Error during update:"
            cat update_response.json
            exit 1
          else
            echo "Assistant updated successfully!"
            cat update_response.json
          fi
