name: Deploy Assistant to OpenAI

on:
  push:
    paths:
      - assistant_config.json

jobs:
  deploy-assistant:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List Files after Checkout
        run: |
          echo "Listing files after checkout:"
          ls -alt /home/runner/work/${{ github.repository }}  # Shows files in the repo root

      - name: Extract Assistant ID
        id: extract-id
        run: |
          CONFIG_FILE="assistant_config.json"

          if [ ! -f "$CONFIG_FILE" ]; then
            echo "Configuration file not found!"
            exit 1
          fi

          # Validate JSON format
          if ! jq empty "$CONFIG_FILE"; then
            echo "Invalid JSON format in $CONFIG_FILE"
            exit 1
          fi

          # Extract assistant ID
          ASSISTANT_ID=$(jq -r '.id // empty' "$CONFIG_FILE")
          if [ -z "$ASSISTANT_ID" ]; then
            echo "Assistant ID not found in $CONFIG_FILE. Exiting."
            exit 1
          fi

          echo "::set-output name=assistant_id::$ASSISTANT_ID" # Pass it as a GitHub Actions output

      - name: List Files Before Running Tests
        run: |
          echo "Listing files before running tests:"
          ls -alt /home/runner/work/${{ github.repository }}  # Shows files in the repo root

      - name: Run Tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          CONFIG_FILE="/home/runner/work/${{ github.repository }}/assistant_config.json"  # Absolute path to the config file
          echo "Listing files before running Python tests:"
          ls -alt /home/runner/work/${{ github.repository }}  # Shows files in the repo root
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python /home/runner/work/${{ github.repository }}/eval_test.py  # Absolute path to the script

      - name: List Files Before Updating Assistant
        run: |
          echo "Listing files before updating assistant:"
          ls -alt /home/runner/work/${{ github.repository }}  # Shows files in the repo root

      - name: Update Assistant on OpenAI
        if: success()  # Only proceed if the tests pass
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          CONFIG_FILE="assistant_config.json"
          ASSISTANT_ID="${{ steps.extract-id.outputs.assistant_id }}"
          API_URL="https://api.openai.com/v1/assistants/$ASSISTANT_ID"

          # Extract relevant fields for update
          jq '{instructions, tools, model}' "$CONFIG_FILE" > temp_config.json

          # Debugging: Display payload
          echo "Payload being sent:"
          cat temp_config.json

          # Execute cURL command
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
            -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "OpenAI-Beta: assistants=v2" \
            -d @temp_config.json \
            "$API_URL")

          # Check response status
          if [ "$RESPONSE" -eq 200 ]; then
            echo "Assistant successfully updated!"
            cat response.json
          else
            echo "Failed to update assistant. HTTP Status: $RESPONSE"
            cat response.json
            exit 1
          fi
