name: Deploy Assistant to OpenAI

on:
  push:
    branches:
      - main

jobs:
  # Job to set up the Python environment and install dependencies
  setup-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12  # Set the Python version you want to use

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest openai

  # Job to set up OpenAI API Key as an environment variable
  setup-api-key:
    runs-on: ubuntu-latest
    needs: setup-environment  # Ensure this runs after setup-environment

    steps:
      - name: Set up OpenAI API Key
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

  # Job to run the tests
  run-tests:
    runs-on: ubuntu-latest
    needs: setup-api-key  # Ensure this runs after the API key is set up

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python virtual environment and run tests
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pytest test_eval_script.py  # Run pytest to execute your test cases

  # Job to extract Assistant ID from the config file
  extract-assistant-id:
    runs-on: ubuntu-latest
    needs: run-tests  # Ensure this runs after tests are executed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract Assistant ID
        id: extract-id
        run: |
          CONFIG_FILE="assistant_config.json"

          if [ ! -f "$CONFIG_FILE" ]; then
            echo "Configuration file not found!"
            exit 1
          fi

          # Validate JSON format
          if ! jq empty "$CONFIG_FILE"; then
            echo "Invalid JSON format in $CONFIG_FILE"
            exit 1
          fi

          # Extract assistant ID
          ASSISTANT_ID=$(jq -r '.id // empty' "$CONFIG_FILE")
          if [ -z "$ASSISTANT_ID" ]; then
            echo "Assistant ID not found in $CONFIG_FILE. Exiting."
            exit 1
          fi

          echo "::set-output name=assistant_id::$ASSISTANT_ID" # Pass it as a GitHub Actions output

  # Job to update Assistant on OpenAI using the extracted Assistant ID
  update-assistant:
    runs-on: ubuntu-latest
    needs: extract-assistant-id  # Ensure this runs after extracting the Assistant ID

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Assistant on OpenAI
        if: success()  # Only proceed if previous jobs were successful
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          CONFIG_FILE="assistant_config.json"
          ASSISTANT_ID="${{ steps.extract-id.outputs.assistant_id }}"
          API_URL="https://api.openai.com/v1/assistants/$ASSISTANT_ID"

          # Extract relevant fields for update
          jq '{instructions, tools, model}' "$CONFIG_FILE" > temp_config.json

          # Debugging: Display payload
          echo "Payload being sent:"
          cat temp_config.json

          # Execute cURL command
          RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
            -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "OpenAI-Beta: assistants=v2" \
            -d @temp_config.json \
            "$API_URL")

          # Check response status
          if [ "$RESPONSE" -eq 200 ]; then
            echo "Assistant successfully updated!"
            cat response.json
          else
            echo "Failed to update assistant. HTTP Status: $RESPONSE"
            cat response.json
            exit 1
