name: Update Assistant to OpenAI

on:
  push:
    paths:
      - assistant_config.json

jobs:
  update-assistant:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Assistant on OpenAI
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ASSISTANT_ID: ${{ secrets.ASSISTANT_ID }}
        run: |
          # Check if ASSISTANT_ID is set
          if [ -z "$ASSISTANT_ID" ]; then
            echo "Error: ASSISTANT_ID is not set in GitHub Secrets."
            exit 1
          fi

          # Validate JSON file
          CONFIG_FILE="assistant_config.json"
          if [ ! -f "$CONFIG_FILE" ]; then
            echo "Configuration file not found: $CONFIG_FILE"
            exit 1
          fi
          if ! jq empty "$CONFIG_FILE"; then
            echo "Invalid JSON format in $CONFIG_FILE"
            exit 1
          fi

          # Remove 'id' field from JSON to avoid conflicts during PATCH
          jq 'del(.id)' "$CONFIG_FILE" > temp_config.json

          # Update the assistant
          echo "Updating the assistant with ID: $ASSISTANT_ID"
          curl -s -X PATCH "https://api.openai.com/v1/assistants/$ASSISTANT_ID" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -H "OpenAI-Beta: assistants=v2" \
            -d @temp_config.json \
            -o update_response.json

          # Check response
          if jq '.error' update_response.json > /dev/null; then
            echo "Error during update:"
            cat update_response.json
            exit 1
          else
            echo "Assistant updated successfully!"
            cat update_response.json
          fi
