name: Deploy Assistant to OpenAI

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Assistant to Dev
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ASSISTANT_ID: ${{ secrets.DEV_ASSISTANT_ID }}
        run: |
          CONFIG_FILE="assistant_config.json"
          API_URL="https://api.openai.com/v1/assistants/$ASSISTANT_ID"

          jq '{instructions, tools, model}' "$CONFIG_FILE" > temp_config.json

          RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
            -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "OpenAI-Beta: assistants=v2" \
            -d @temp_config.json \
            "$API_URL")

          if [ "$RESPONSE" -eq 200 ]; then
            echo "Dev update successful!"
            cat response.json
          else
            echo "Dev update failed: $RESPONSE"
            cat response.json
            exit 1
          fi

  run-tests:
    name: Run Tests
    needs: deploy-dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Tests
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pytest test_eval_script.py

  deploy-prod:
    name: Deploy to Prod
    needs: run-tests
    runs-on: ubuntu-latest
    environment:
      name: production
      # Manual approval required via GitHub Environments

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Assistant to Prod
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ASSISTANT_ID: ${{ secrets.PROD_ASSISTANT_ID }}
        run: |
          CONFIG_FILE="assistant_config.json"
          API_URL="https://api.openai.com/v1/assistants/$ASSISTANT_ID"

          jq '{instructions, tools, model}' "$CONFIG_FILE" > temp_config.json

          RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
            -X POST \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "OpenAI-Beta: assistants=v2" \
            -d @temp_config.json \
            "$API_URL")

          if [ "$RESPONSE" -eq 200 ]; then
            echo "Prod update successful!"
            cat response.json
          else
            echo "Prod update failed: $RESPONSE"
            cat response.json
            exit 1
          fi
